### ISSUE TITLE
Reconfiguration understanding

### ISSUE THREAD

**Issue by MeatballCat** [sane-lab/Trisk#2]
Hi, Mao
I have some questions. I hope I can ask you for help.
1.In essence, does your controller realize the diversity of reconfiguration by modifying the parallelism of different operators?
2.I want to understand the implementation process of your whole controller, that is, where should I start to track and debug in a complete program running cycle?
Looking forward to your reply, thank you.

**Comment by MeatballCat** [comment]
Hi, Mao
When I use your script for reconfiguration, I find that the parallelism of the operator has changed in the standalone, but when I test in yarn, the parallelism of the operator has not changed. Would you please take the time to reply to me? thank you

**Comment by yancanmao** [comment]
Hi,

The answers are as follows:

1.In essence, does your controller realize the diversity of reconfiguration by modifying the parallelism of different operators?

By far, our functionalities support OneInputStreamProcessor in Flink i.e., there will only have one stream and its associated state backend. There are some advanced operations such as Hash Join requiring two separate state backends,  which requires more engineering efforts to be integrated. Nevertheless, our implementation is enough to support reconfigurations on Map, Window, and normal Join operators in Flink.

2.I want to understand the implementation process of your whole controller, that is, where should I start to track and debug in a complete program running cycle?

As we mentioned in the README, you are supposed to start from StreamManager, which will launch the controllers for the associated applications.

3.When I use your script for reconfiguration, I find that the parallelism of the operator has changed in the standalone, but when I test in yarn, the parallelism of the operator has not changed. 

We have implemented our functionalities in the Standalone cluster. Because YARN cluster and Standalone have different entrypoint in Flink implementation, YARN is not supported yet.

**Comment by MeatballCat** [comment]
I see, thank you very much for your patient reply.
